brew cask install "java" --no-quarantine
brew cask install "xquartz" --no-quarantine
brew cask install "alfred" --no-quarantine
brew cask install "android-ndk" --no-quarantine
brew cask install "android-sdk" --no-quarantine
brew cask install "android-studio" --no-quarantine
brew cask install "appcleaner" --no-quarantine
brew cask install "bartender" --no-quarantine
brew cask install "betterzipql" --no-quarantine
brew cask install "brave" --no-quarantine
brew cask install "caffeine" --no-quarantine
brew cask install "couleurs" --no-quarantine
brew cask install "docker" --no-quarantine
brew cask install "dotnet" --no-quarantine
brew cask install "dotnet-sdk" --no-quarantine
brew cask install "eclipse-ide" --no-quarantine
brew cask install "endurance" --no-quarantine
brew cask install "firefox" --no-quarantine
brew cask install "ghost" --no-quarantine
brew cask install "gimp" --no-quarantine
brew cask install "gitter" --no-quarantine
brew cask install "google-chrome" --no-quarantine
brew cask install "google-drive" --no-quarantine
brew cask install "handbrake" --no-quarantine
brew cask install "hyper" --no-quarantine
brew cask install "inkscape" --no-quarantine
brew cask install "iterm2" --no-quarantine
brew cask install "kap" --no-quarantine
brew cask install "kindle" --no-quarantine
brew cask install "kitematic" --no-quarantine
brew cask install "openshot-video-editor" --no-quarantine
brew cask install "path-finder" --no-quarantine
brew cask install "postman" --no-quarantine
brew cask install "qlcolorcode" --no-quarantine
brew cask install "qlimagesize" --no-quarantine
brew cask install "qlmarkdown" --no-quarantine
brew cask install "qlprettypatch" --no-quarantine
brew cask install "qlstephen" --no-quarantine
brew cask install "quicklook-csv" --no-quarantine
brew cask install "quicklook-json" --no-quarantine
brew cask install "resilio-sync" --no-quarantine
brew cask install "skitch" --no-quarantine
brew cask install "slack" --no-quarantine
brew cask install "sublime-text" --no-quarantine
brew cask install "the-unarchiver" --no-quarantine
brew cask install "vagrant" --no-quarantine
brew cask install "virtualbox" --no-quarantine
brew cask install "vlc" --no-quarantine
brew cask install "visual-studio-code" --no-quarantine
brew cask install "caskroom/drivers/garmin-express" --no-quarantine
brew cask install "caskroom/fonts/font-awesome-terminal-fonts" --no-quarantine
brew cask install "caskroom/fonts/font-hack" --no-quarantine
brew cask install "caskroom/fonts/font-inconsolata-dz-for-powerline" --no-quarantine
brew cask install "caskroom/fonts/font-inconsolata-for-powerline" --no-quarantine
brew cask install "caskroom/fonts/font-inconsolata-g-for-powerline" --no-quarantine
brew cask install "caskroom/fonts/font-roboto-mono" --no-quarantine
brew cask install "caskroom/fonts/font-roboto-mono-for-powerline" --no-quarantine
brew cask install "caskroom/fonts/font-source-code-pro" --no-quarantine
brew cask install "caskroom/versions/airmail-beta" --no-quarantine
brew cask install "caskroom/versions/microsoft-remote-desktop-beta" --no-quarantine